[tool.black]
line-length = 100
preview = true

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
src = ["app", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
pretty = true
ignore_missing_imports = true
exclude = [
  "alembic",
  "venv",
  "tests",
]
