"""Add threshold performance logs table

Revision ID: 17075766d8b1
Revises: 507bca9328cd
Create Date: 2025-08-05 12:47:59.406755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17075766d8b1'
down_revision = '507bca9328cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###