"""Fix metadata column name in threshold performance logs

Revision ID: 238f01d5a2b5
Revises: 17075766d8b1
Create Date: 2025-08-05 13:00:35.558467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238f01d5a2b5'
down_revision = '17075766d8b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###