"""Add user settings table

Revision ID: 8c037bb691f0
Revises: 7a6fea689cdc
Create Date: 2025-07-28 03:17:44.138731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c037bb691f0'
down_revision = '7a6fea689cdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('default_llm_provider', sa.String(length=50), nullable=True),
    sa.Column('default_embedding_provider', sa.String(length=50), nullable=True),
    sa.Column('max_conversation_history', sa.Integer(), nullable=True),
    sa.Column('auto_save_conversations', sa.Boolean(), nullable=True),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint(op.f('bot_permissions_bot_id_user_id_key'), 'bot_permissions', type_='unique')
    op.create_unique_constraint('uq_bot_user', 'bot_permissions', ['bot_id', 'user_id'])
    op.alter_column('messages', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_api_keys_user_id_provider_key'), 'user_api_keys', type_='unique')
    op.create_unique_constraint('uq_user_provider', 'user_api_keys', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_provider', 'user_api_keys', type_='unique')
    op.create_unique_constraint(op.f('user_api_keys_user_id_provider_key'), 'user_api_keys', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.alter_column('messages', 'message_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_bot_user', 'bot_permissions', type_='unique')
    op.create_unique_constraint(op.f('bot_permissions_bot_id_user_id_key'), 'bot_permissions', ['bot_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_settings')
    # ### end Alembic commands ###