"""Add frontend logs table

Revision ID: 9ca6c6c94175
Revises: 687a18e55dc0
Create Date: 2025-08-11 12:25:20.900541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca6c6c94175'
down_revision = '687a18e55dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###