"""Add collection metadata and dimension validation tables

Revision ID: d3abd8fc2bbf
Revises: 8c037bb691f0
Create Date: 2025-08-04 12:07:54.569059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3abd8fc2bbf'
down_revision = '8c037bb691f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###