"""Add threshold performance logs table properly

Revision ID: fa6004ffe520
Revises: 238f01d5a2b5
Create Date: 2025-08-05 13:17:15.858139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6004ffe520'
down_revision = '238f01d5a2b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###